vorobeyme_jobeet_job:
    resource: "@VorobeymeJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

vorobeyme_jobeet_homepage:
    path:     /
    defaults: { _controller: VorobeymeJobeetBundle:Job:index }
