vorobeyme_jobeet_job:
    resource: "@VorobeymeJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

vorobeyme_jobeet_category:
    path: 	  "/category/{slug}/{page}"
    defaults: { _controller: VorobeymeJobeetBundle:Category:show, page: 1 }

vorobeyme_jobeet_homepage:
    path:  /
    defaults: { _controller: VorobeymeJobeetBundle:Job:index }
